In [42]:
import pandas as pd
import numpy as np
path= "C:/Users/Dell/OneDrive/Documentos/UCC_FILING_FINAL.xlsx" #just use read_excel from pd and it will make the work easier. No need for other tools

In [43]:
UCC= pd.read_excel(path)
UCC= UCC.sort_values(by='DealName', ascending=True) #If ascending=False, is the same as typing 'descend' in matlab.
UCC_Deal= UCC #Create a copy to ensure no overwritting.
type(UCC_Deal) #lets see how the table is organized
UCC_Deal

,DealName,Stage,Tranche,M2Paid,UCCFiled,AccountName_AccountName_,M2CertificateSignedDate,CustomerState,Asignado
0,Aanjo Premlal 705 Shrewsbury Pl,Funded,Inception Financial Development LLC Tranche 20...,Yes,Done,Hub City Solar,2024-04-25,TX,NaN
1,Aaron Farrar 7989 FM 749,Funded,MB Market Solar24 LLC Tranche 2024-04-18,Yes,Done,Hub City Solar,2024-04-26,TX,NaN
2,Aaron Haynes 6609 Coral Ln,NaN,NaN,NaN,Done,NaN,NaT,TX,NaN
3,Abdul Kaiyum 2099 Timineri Dr,Funded,Inception Solar LLC Tranche 2024-12-02,Yes,Done,Dawn to Dusk Solar,2025-02-26,TX,NaN
4,Abel Gonzalez 4731 Charriton Dr,NaN,NaN,NaN,Done,NaN,NaT,TX,NaN
...,...,...,...,...,...,...,...,...,...
2148,Yvonne Soliz 2130 Shirley Dr,Funded,Fairtide Operating Delta LLC Tranche 2024-12-05,Yes,Done,Lone Star Solar Services LLC,2024-12-23,TX,NaN
2149,Zach Hall 3507 Tulip Trace Dr,Funded,Inception Solar LLC Tranche 2024-12-26,Yes,Done,"TriSMART Solar, LLC",2025-04-11,TX,NaN
2150,Zanetta Crim 803 N Elm St,NaN,NaN,NaN,Done,NaN,NaT,TX,NaN
2151,Zorayda Limon 305 5th St,Funded,Fairtide Operating Delta LLC Tranche 2024-12-18,Yes,Done,Simplicity Power LLC,2025-01-21,TX,NaN
2152,Zorayda Limon 305 5th St,Funded,Fairtide Operating Delta LLC Tranche 2024-12-18,Yes,Done,Simplicity Power LLC,2025-01-21,TX,NaN

In [44]:
List_path= "C:/Users/Dell/Desktop/trabajo/uccs/ucc_lists.txt"
deal_list=[] #create the deal name list to work with.
type(deal_list)
with open(List_path,"r+") as deals:
    deals.seek(0)
    for deal in deals:
         deal_list.append(deal.strip()) #do not set the result back to deal_list, it is incorrect syntax.
length= len(deal_list)

In [47]:
i=0
not_found=[]
for deal in deal_list:
     ##if any(UCC_Deal.loc[UCC_Deal['DealName'] == deal]):
     #It “works” but not for the reason you might expect—it’s not truly checking “does at least one row match my condition,” 
#but rather “is there any truthy value in these columns,”
#which just happens to align with your goal in this case.  
    if not UCC_Deal.loc[UCC_Deal['DealName'] == deal].empty: #This approach is more adequate since it actually follows my logic
        UCC_Deal.loc[UCC_Deal['DealName'] == deal, 'UCCFiled']= 'Done'
        i=i+1
    else:
        not_found.append(deal)

In [48]:
if i!=length:
    print("It appears that not all deals were found")
else:
    print("All deals were found")
not_found
#Try looking first by the address and then continue with the name. Usually the address is fine.

It appears that not all deals were found

['Irma Rodriguez The Preserve at Dyer Creek 1120 Preserve Pl',
 'Arash Debhdari 7370 Sleepy Ridge Cir',
 'Francisco J Martínez 103 Catalina Dr',
 'Navayakrishna Bandaru 611 Lily Ln',
 'Richard Llanes 707 Pine St']

In [49]:
#Now that we are getting  closer to the end, lets pass the information from UCC_Deal to the original excel.
UCC_Deal.to_excel(path, index=False) #index=false prevents Pandas from writting an additional column containing the indexes of the DF.
#Don't get scared if your excel format gets lost in the process. At this point , you are mostly just going to be uploading UCC File docs.